--INSERTION DES PRODUITS
SET SERVEROUTPUT ON
SET VERIFY OFF

ACCEPT NOM_PRODUIT PROMPT "ENTRER LE NOM DU PRODUIT: "
ACCEPT QUANTITE_PRODUIT PROMPT "ENTRER LA QUANTITE EN STOCK DU PRODUIT: "
ACCEPT PRIX_PRODUIT PROMPT "ENTRER LE PRIX DU PRODUIT: "


DECLARE
	ERREUR_INTEGRITE EXCEPTION;
	PRAGMA EXCEPTION_INIT(ERREUR_INTEGRITE, -2291);
	
	NOMPR         ENTREPOT.PRODUITS.NOM%TYPE := '&NOM_PRODUIT';
	QUANTITEPR    ENTREPOT.PRODUITS.QUANTITESTOCK%TYPE := '&QUANTITE_PRODUIT';
	PRIXPR        ENTREPOT.PRODUITS.PRIX%TYPE := '&PRIX_PRODUIT' ;
	


BEGIN
	INSERT INTO ENTREPOT.PRODUITS(
		NUMPROD,
		NOM,
		QUANTITESTOCK,
		PRIX
	)VALUES(
		Entrepot.NUMPRODUITS_SEQ.NEXTVAL,
		NOMPR,
		QUANTITEPR,
		PRIXPR
	);
	COMMIT;
	DBMS_OUTPUT.PUT_LINE('PRODUIT INSERE AVEC SUCCES.');

EXCEPTION
    WHEN ERREUR_INTEGRITE THEN
        DBMS_OUTPUT.PUT_LINE('ERREUR: VIOLATION DE CONTRAINTE  D''INTEGRITE.');
        ROLLBACK;
	WHEN DUP_VAL_ON_INDEX THEN
		DBMS_OUTPUT.PUT_LINE('LE CODE EXISTE DEJA!');	
	WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERREUR: ' || SQLERRM);
        ROLLBACK;
END;
/
SET verify ON
@C:\ApexScripts\APEXMENU.SQL

