--INSERTION DES CLIENTS.SQL
SET SERVEROUTPUT ON
SET VERIFY OFF

ACCEPT NOM PROMPT "ENTRER LE NOM DU CLIENT: "
ACCEPT PRENOM PROMPT "ENTRER LE PRENOM DU CLIENT: "
ACCEPT TELEPHONE PROMPT "ENTRER LE TELEPHONE DU CLIENT: "
ACCEPT NORUE PROMPT "ENTRER LE NUMERO DE SON ADRESSE: "
ACCEPT NOMRUE PROMPT "ENTRER LE NOM DE SA RUE: "
ACCEPT VILLE PROMPT "ENTRER SA VILLE: "
ACCEPT PROVINCE PROMPT "ENTRER SA PROVINCE: "
ACCEPT CODEPOSTAL PROMPT "ENTRER SON CODE POSTAL: "
ACCEPT PAYS PROMPT "ENTRER SON PAYS: "

DECLARE
	ERREUR_INTEGRITE EXCEPTION;
	PRAGMA EXCEPTION_INIT(ERREUR_INTEGRITE, -2291);
	
	INVALID_PHONE_NUMBER EXCEPTION;
    INVALID_POSTAL_CODE EXCEPTION;
	
	NOMCL ENTREPOT.CLIENTS.NOMCLIENT%TYPE := '&NOM';
	PRENCL ENTREPOT.CLIENTS.PRENOMCLIENT%TYPE := '&PRENOM';
	TELCL ENTREPOT.CLIENTS.TELEPHONE%TYPE := '&TELEPHONE' ;
	RUECL ENTREPOT.CLIENTS.NORUE%TYPE := '&NORUE';
	NOMRUECL ENTREPOT.CLIENTS.NOMRUE%TYPE := '&NOMRUE';
	VILLECL ENTREPOT.CLIENTS.VILLE%TYPE := '&VILLE';
	PROVINCECL ENTREPOT.CLIENTS.PROVINCE%TYPE:= '&PROVINCE';
	CODEPOSTALCL ENTREPOT.CLIENTS.CODEPOSTAL%TYPE:= '&CODEPOSTAL';
	PAYSCL ENTREPOT.CLIENTS.PAYS%TYPE:= '&PAYS';
	
BEGIN

	IF NOT REGEXP_LIKE(TELCL, '^\(\d{3}\)\d{3}-\d{4}$') THEN
        RAISE INVALID_PHONE_NUMBER;
    END IF;

    -- Validate postal code
	IF NOT REGEXP_LIKE(CODEPOSTALCL, '^[A-Z]\d[A-Z]\d[A-Z]\d$') THEN
        RAISE INVALID_POSTAL_CODE;
    END IF;

	INSERT INTO ENTREPOT.CLIENTS(
		NUMCLIENT,
		NOMCLIENT,
        PRENOMCLIENT,
        TELEPHONE,
        NORUE,
        NOMRUE,
        VILLE,
        PROVINCE,
        CODEPOSTAL,
        PAYS
	)VALUES (
		Entrepot.NUMCLIENTS_SEQ.NEXTVAL,
		NOMCL,
        PRENCL,
        TELCL,
        RUECL,
        NOMRUECL,
        VILLECL,
        PROVINCECL,
        CODEPOSTALCL,
        PAYSCL
    );
	 COMMIT;
	 DBMS_OUTPUT.PUT_LINE('CLIENT INSERE AVEC SUCCES.');

EXCEPTION
    WHEN ERREUR_INTEGRITE THEN
        DBMS_OUTPUT.PUT_LINE('ERREUR: VIOLATION DE CONTRAINTE  D''INTEGRITE.');
        ROLLBACK;
	WHEN DUP_VAL_ON_INDEX THEN
		DBMS_OUTPUT.PUT_LINE('LE CODE EXISTE DEJA!');
	WHEN INVALID_POSTAL_CODE THEN
		DBMS_OUTPUT.PUT_LINE('ERREUR: VOUS N''AVEZ PAS ECRIE UN CODE POSTAL VALIDE.');
    WHEN INVALID_PHONE_NUMBER THEN
		DBMS_OUTPUT.PUT_LINE('ERREUR: VOUS N''AVEZ PAS ECRIE UN NUMERO DE TELEPHONE VALIDE.');
	WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERREUR: ' || SQLERRM);
        ROLLBACK;
END;
/
SET verify ON
@C:\ApexScripts\APEXMENU.SQL